### ISSUE TITLE
It does not work to Korean services.

### ISSUE THREAD

**Issue by tjholic** [kubero-dev/ladder#10]
It does not work with the column service called "longblack".

https://1ft.io/proxy?q=https%3A%2F%2Fwww.longblack.co%2Fnote%2F875

**Comment by mms-gianni** [comment]
Hi
I had a quick look into it. 

Not every paywall can be removed. This seems to be one of these. 

The ladder works only if the content is visible to Google bots, or hidden by some CSS Overlays.
